artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  local_data_dir: artifacts/data_ingestion/customer_booking.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  source_data_path: artifacts/data_ingestion/customer_booking.csv
  local_data_path: artifacts/data_transformation/cleaned_customer_booking.csv
  transformed_root_dir: artifacts/data_transformation/transformed
  transformed_data_train_feature: artifacts/data_transformation/transformed/train_features.csv
  transformed_data_test_feature: artifacts/data_transformation/transformed/test_features.csv
  transformed_data_train_label: artifacts/data_transformation/transformed/train_label.csv
  transformed_data_test_label: artifacts/data_transformation/transformed/test_label.csv
  train_file: artifacts/data_transformation/train.csv
  test_file: artifacts/data_transformation/test.csv


model_training:
  root_dir: artifacts/model_training
  train_data_features: artifacts/data_transformation/transformed/train_features.csv
  train_data_label: artifacts/data_transformation/transformed/train_label.csv
  model_name: artifacts/model_training/br_model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  train_data_features: artifacts/data_transformation/transformed/train_features.csv
  train_data_label: artifacts/data_transformation/transformed/train_label.csv
  test_data_features: artifacts/data_transformation/transformed/test_features.csv
  test_data_label: artifacts/data_transformation/transformed/test_label.csv
  model_path: artifacts/model_training/br_model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
